ALTER TABLE jobs ADD COLUMN preset TEXT NOT NULL DEFAULT 'balanced';
ALTER TABLE jobs ADD COLUMN solver TEXT NOT NULL DEFAULT 'Midpoint';
ALTER TABLE jobs ADD COLUMN number_function_evaluations INTEGER NOT NULL DEFAULT 64;
ALTER TABLE jobs ADD COLUMN prior_temperature REAL NOT NULL DEFAULT 0.5;
ALTER TABLE jobs ADD COLUMN output_choice TEXT NOT NULL DEFAULT 'enhanced';
