ALTER TABLE upload_intents ADD COLUMN noise_removal INTEGER NOT NULL DEFAULT 0;
ALTER TABLE upload_intents ADD COLUMN enhance INTEGER NOT NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN noise_removal INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN enhance INTEGER NOT NULL DEFAULT 1;
